server:
    port: 6000
spring:
    cloud:
        config:
            server:
                git:
                    default-label: eureka
                    uri: https://github.com/rodrigosy03/microservicios-cursos-virtuales
                    search-paths: config-data
    application:
        name: config-service
